In [1]:
import pandas as pd

In [2]:
# Create a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print(" list:", numbers)

 list: [10, 20, 30, 40, 50]


In [4]:
# append()
numbers.append(60)
print("After append:", numbers)

After append: [10, 20, 30, 40, 50, 60, 60]


In [6]:
# extend()
numbers.extend([70, 80])
print("After extend:", numbers)

After extend: [10, 20, 30, 40, 50, 60, 60, 70, 80, 70, 80]


In [10]:
# insert()
numbers.insert(2, 25)   # insert 25 at index 2
print("After insert:", numbers)

After insert: [10, 20, 25, 25, 25, 30, 40, 50, 60, 60, 70, 80, 25, 70, 80]


In [11]:
# remove()
numbers.remove(40)      # remove value 40
print("After remove:", numbers)

After remove: [10, 20, 25, 25, 25, 30, 50, 60, 60, 70, 80, 25, 70, 80]


In [12]:
# pop()
popped_value = numbers.pop()  # removes last element
print("After pop():", numbers)
print("Popped value:", popped_value)


After pop(): [10, 20, 25, 25, 25, 30, 50, 60, 60, 70, 80, 25, 70]
Popped value: 80


In [13]:
# index()
index_of_25 = numbers.index(25)
print("Index of 25:", index_of_25)

Index of 25: 2


In [14]:
# count()
count_of_20 = numbers.count(20)
print("Count of 20:", count_of_20)

Count of 20: 1


In [15]:
# sort()
numbers.sort()
print("After sort():", numbers)

After sort(): [10, 20, 25, 25, 25, 25, 30, 50, 60, 60, 70, 70, 80]


In [16]:
# reverse()
numbers.reverse()
print("After reverse():", numbers)

After reverse(): [80, 70, 70, 60, 60, 50, 30, 25, 25, 25, 25, 20, 10]


In [17]:
# clear()
numbers.clear()
print("After clear():", numbers)

After clear(): []


In [20]:
# Create a tuple with 3 student names
students = ("Aman", "Riya", "Khan")
print(" tuple:", students)

 tuple: ('Aman', 'Riya', 'Khan')


In [21]:
students[1] = "Simran"

TypeError: 'tuple' object does not support item assignment

In [ ]:
#Reason of the error:-
Because tuples are immutable in Python.
That means once a tuple is created, you cannot change, add, or remove its elements.

In [22]:
# Create a set with duplicate values
numbers = {10, 20, 30, 30, 10, 40}
print("Set:", numbers)

Set: {40, 10, 20, 30}


In [23]:
#Explanation: Does not allow duplicate values

In [25]:
# Create a dictionary
student = {
    "name": "Aman",
    "age": 23,
    "city": "Hydrabad"
}

print("Original dictionary:", student)


Original dictionary: {'name': 'Aman', 'age': 23, 'city': 'Hydrabad'}


In [28]:
# Update the age
student["age"] = 24

# Add a new key 'email'
student["email"] = "aman@gmail.com"

In [29]:
print("Final dictionary:", student)

Final dictionary: {'name': 'Aman', 'age': 24, 'city': 'Hydrabad', 'email': 'aman@gmail.com'}


In [30]:

age = 17  
if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")

You are not eligible to vote.


In [31]:
# Given marks
marks = 82   # you can change this value

In [32]:
# Check grade
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")


Grade: B


In [33]:
# Given number
num = 3   

if num > 0:
    print("The number is positive.")
    
    # Check if positive number is even
    if num % 2 == 0:
        print("It is also even.")
    else:
        print("It is not even.")
        
elif num == 0:
    print("The number is zero.")
    
else:
    print("The number is negative.")


The number is positive.
It is not even.


In [34]:
#Section B

In [35]:
import numpy as np
# Scalar
scalar = np.array(5)
print("Scalar:\n", scalar)

Scalar:
 5


In [36]:
# 1D array with values 1 to 5
arr_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:\n", arr_1d)



1D Array:
 [1 2 3 4 5]


In [39]:
# 2D array 
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("\n2D Array :\n", arr_2d)


2D Array :
 [[10 20 30]
 [40 50 60]]


In [40]:
# Generate a 4x4 array of random integers between 0 and 100

arr = np.random.randint(0, 101, size=(4, 4))

print("4x4 Random Integer Array:\n", arr)


4x4 Random Integer Array:
 [[12 93  1 64]
 [39 53 72 40]
 [41 68 16 58]
 [44 30 47 10]]


In [41]:
import numpy as np
import pandas as pd

# Create a 3x3 numpy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [42]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
# Convert to DataFrame with column names
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

In [44]:
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [45]:
#Section C

In [46]:
import pandas as pd
import numpy as np

# Creating a DataFrame 
data = {
    'Name': ['Aman', 'Sameer', 'Tanveer', 'Aman', 'Sara', 'Ali', 'Sameer', 'Meera', 'Suraj', 'Tanveer'],
    'Age': [25, 30, 28, 25, 22, 35, 30, 29, 40, 28],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Delhi', 'Pune', 'Chennai', 'Mumbai', 'Delhi', 'Kolkata', 'Delhi'],
    'Salary': [50000, 60000, np.nan, 50000, 45000, 70000, 60000, 58000, np.nan, 52000]
}

In [47]:
df = pd.DataFrame(data)

In [48]:
df

Name  Age     City   Salary
0     Aman   25    Delhi  50000.0
1   Sameer   30   Mumbai  60000.0
2  Tanveer   28    Delhi      NaN
3     Aman   25    Delhi  50000.0
4     Sara   22     Pune  45000.0
5      Ali   35  Chennai  70000.0
6   Sameer   30   Mumbai  60000.0
7    Meera   29    Delhi  58000.0
8    Suraj   40  Kolkata      NaN
9  Tanveer   28    Delhi  52000.0

In [50]:
# 2. Display info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [51]:
df.describe()

Age       Salary
count  10.000000      8.00000
mean   29.200000  55625.00000
std     5.181162   7927.12342
min    22.000000  45000.00000
25%    25.750000  50000.00000
50%    28.500000  55000.00000
75%    30.000000  60000.00000
max    40.000000  70000.00000

In [53]:
# 4. Select 'Name' and 'City' columns
print(df[['Name', 'City']])

      Name     City
0     Aman    Delhi
1   Sameer   Mumbai
2  Tanveer    Delhi
3     Aman    Delhi
4     Sara     Pune
5      Ali  Chennai
6   Sameer   Mumbai
7    Meera    Delhi
8    Suraj  Kolkata
9  Tanveer    Delhi


In [54]:
# 5. Drop 'City' column
df_dropped = df.drop(columns=['City'])

In [55]:
df_dropped

Name  Age   Salary
0     Aman   25  50000.0
1   Sameer   30  60000.0
2  Tanveer   28      NaN
3     Aman   25  50000.0
4     Sara   22  45000.0
5      Ali   35  70000.0
6   Sameer   30  60000.0
7    Meera   29  58000.0
8    Suraj   40      NaN
9  Tanveer   28  52000.0

In [56]:
# 6. Fill missing values in Salary with mean
mean_salary = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(mean_salary)

In [57]:
df

Name  Age     City   Salary
0     Aman   25    Delhi  50000.0
1   Sameer   30   Mumbai  60000.0
2  Tanveer   28    Delhi  55625.0
3     Aman   25    Delhi  50000.0
4     Sara   22     Pune  45000.0
5      Ali   35  Chennai  70000.0
6   Sameer   30   Mumbai  60000.0
7    Meera   29    Delhi  58000.0
8    Suraj   40  Kolkata  55625.0
9  Tanveer   28    Delhi  52000.0

In [59]:
# 7. Remove duplicate rows
df_unique = df.drop_duplicates()

In [60]:
df_unique

Name  Age     City   Salary
0     Aman   25    Delhi  50000.0
1   Sameer   30   Mumbai  60000.0
2  Tanveer   28    Delhi  55625.0
4     Sara   22     Pune  45000.0
5      Ali   35  Chennai  70000.0
7    Meera   29    Delhi  58000.0
8    Suraj   40  Kolkata  55625.0
9  Tanveer   28    Delhi  52000.0